import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import NoiseBackground from "@/components/ui/NoiseBackground";

const konexy = localFont({
  src: "../../public/font/KonexyPersonalUse.otf",
  variable: "--font-konexy",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${konexy.variable} antialiased mx-8 my-4`}
      >
        <NoiseBackground />
        {children}
      </body>
    </html>
  );
}
